package com.domain.pojo;
// Generated Jan 13, 2018 12:41:00 AM by Hibernate Tools 4.3.1



/**
 * Test generated by hbm2java
 */
public class Test  implements java.io.Serializable {


     private Integer id;
     private String name;

    public Test() {
    }

    public Test(String name) {
       this.name = name;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }




}


